### ISSUE TITLE
Add authors contacts to articles

### ISSUE THREAD

**Issue by DecoyRS** [TheToolsmiths/TheToolsmiths.github.io#18]
Create DB of authors in `_data` with links to social networks.
Example:
```
// authors.db
- name: Name Surname
  connections:
  - GitHub:  https://github.com/DecoyRS
  - Slack: https://thetoolsmiths.slack.com/messages/D4R0RB5FT/

// social_networks.db
- GitHub: assets/icons/GitHub.png
- Slack: assets/icons/Slack.png
```
This information should show up on the page as icons for corresponding networks, e.g. GitHub - OctoPuss, Slack - "Slack's hashtag symbol" with link to Toolsmiths slack with direct message link to the author, etc.
